/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __CH582_IIC__H
#define __CH582_IIC__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_CH582_IIC(Args *args);

void CH582_IIC_platformDisable(PikaObj *self);
void CH582_IIC_platformEnable(PikaObj *self);
void CH582_IIC_platformRead(PikaObj *self);
void CH582_IIC_platformWrite(PikaObj *self);

#endif
